enum PsPointPosition
{
    PS_POSITION_TOP_LEFT,
    PS_POSITION_TOP_RIGHT,
    PS_POSITION_BOTTOM_LEFT,
    PS_POSITION_BOTTOM_RIGHT,
    PS_POSITION_STOP_LEFT,
    PS_POSITION_STOP_RIGHT
};

enum PsPointQuality
{
    PS_QUALITY_LOW,
    PS_QUALITY_HIGH
};

enum ParkingType
{
    PARKING_TYPE_VERTICAL,
    PARKING_TYPE_LATERAL,
    PARKING_TYPE_OBLIQUE,
    PARKING_TYPE_NONE
};

enum ParkingSpaceSize
{
    PARKING_SPACE_SIZE_NORMAL,
    PARKING_SPACE_SIZE_SMALL,
    PARKING_SPACE_SIZE_NARROW
};

enum ParkingStatus
{
    PARKING_STATUS_FREE,
    PARKING_STATUS_OCCUPIED,
    PARKING_STATUS_UNKOWN
};

enum ParkingSensorType
{
    PARKING_SENSOR_CAMERA,
    PARKING_SENSOR_MAP,
    PARKING_SENSOR_CAM_MAP_FUSION,
    PARKING_SENSOR_USS
};

enum GearPosition
{
    GEAR_NEUTRAL,
    GEAR_DRIVE,
    GEAR_REVERSE,
    GEAR_PARKING,
    GEAR_LOW,
    GEAR_INVALID,
    GEAR_NONE
};

enum PlanningTrajectoryType
{
    TRAJECTORY_TYPE_UNKNOWN,
    TRAJECTORY_TYPE_NORMAL,
    TRAJECTORY_TYPE_PATH_FALLBACK,
    TRAJECTORY_TYPE_SPEED_FALLBACK,
    TRAJECTORY_TYPE_PATH_REUSED,
    TRAJECTORY_TYPE_SHORT_PATH,
    TRAJECTORY_TYPE_PATH_LANE_KEEP,
    TRAJECTORY_TYPE_PATH_LANE_CHANGE,
    TRAJECTORY_TYPE_PATH_PULL_OVER
};

struct Header
{
    uint64 seq;
    string frame_id;
    uint64 publish_stamp_ms;
    uint64 data_stamp_ms;
};

struct Point3D
{
    double x;
    double y;
    double z;
};

struct PsPoint
{
    Point3D point;
    PsPointPosition position;
    PsPointQuality quality;
};

struct ParkingPathPoint
{
    double x;
    double y;
    double z;
    double yaw;
    double accumulate_s;
    uint32 gear;
};

struct ParkingLot
{
    uint32 parking_seq;
    ParkingType type;
    ParkingStatus status;
    ParkingSensorType sensor_type;
    boolean is_private_ps;
    sequence<PsPoint> pts_vrf;
    double time_creation;
    sequence<PsPoint> pts_enu;
    double hmi_angle;
    double hmi_depth;
    double hmi_width;
    double hmi_direction;
    double hmi_type;
    double hmi_status;
    ParkingSpaceSize park_size;
};

struct SelectedSlot
{
    Header header;
    uint32 count;
    uint32 loc_seq;
    uint32 opt_parking_seq;
    sequence<ParkingLot> parking_lots;
    boolean is_valid;
    uint32 path_point_size;
    sequence<ParkingPathPoint> traced_path;
    boolean hpp_cruising_to_parking;
    boolean enable_trigger;
};

struct PathPoint
{
    double x;
    double y;
    double z;
    double theta;
    double kappa;
    double s;
    double l;
    double dkappa;
    double ddkappa;
    string lane_id;
    double x_derivative;
    double y_derivative;
};

struct GaussianInfo
{
    double sigma_x;
    double sigma_y;
    double correlation;
    double area_probability;
    double ellipse_a;
    double ellipse_b;
    double theta_a;
};

struct TrajectoryPoint
{
    PathPoint path_point;
    double v;
    double a;
    double relative_time;
    double da;
    double steer;
    GaussianInfo gaussian_info;
};

struct EStop
{
    boolean is_estop;
    string reason;
};

struct PlanningTrajectory
{
    Header header;
    double total_path_length;
    double total_path_time;
    sequence<TrajectoryPoint> trajectory_point;
    boolean is_replan;
    uint32 replan_type;
    string replan_reason;
    double longitudinal_diff;
    double lateral_diff;
    GearPosition gear;
    EStop estop;
    PlanningTrajectoryType trajectory_type;
};
